# Generated by Django 3.2.11 on 2022-03-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classperiod', models.DateTimeField(default=False)),
                ('stardate', models.DateTimeField()),
                ('finaldate', models.DateTimeField()),
                ('section', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name_m', models.CharField(max_length=30)),
                ('typeofmatter', models.CharField(max_length=12)),
                ('picture', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('record', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom')),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.matter')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teacher', models.CharField(max_length=15)),
                ('first_teacher', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to=None)),
                ('category', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=12)),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.matter')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField()),
                ('status', models.BooleanField(max_length=1)),
                ('name', models.CharField(max_length=15)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.students')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='matter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.matter'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.professor'),
        ),
    ]
