# Generated by Django 3.2.11 on 2022-02-09 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Config_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefin', models.DateField()),
                ('contenido_id', models.FileField(max_length=10, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name_m', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_admin', models.CharField(max_length=10)),
                ('user_mod', models.CharField(max_length=10)),
                ('user_doc', models.CharField(max_length=10)),
                ('user_est', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clase')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.materia')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=25)),
                ('support_material', models.FileField(upload_to=None)),
                ('fecha_nc', models.DateTimeField()),
                ('contenido', models.FileField(upload_to=None)),
                ('Profesor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profesor')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clase')),
                ('config_bot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.config_bot')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Est_grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clase')),
                ('usuario_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entregar_asig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_date', models.DateTimeField()),
                ('status_notifies', models.BooleanField(max_length=1)),
                ('evaluacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.evaluation')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='config_bot',
            name='profesor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profesor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='materia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.materia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipo_user'),
            preserve_default=False,
        ),
    ]
