# Generated by Django 3.2.11 on 2022-02-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=20)),
                ('permission_level', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='Tipo_user',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertype'),
        ),
    ]
