# Generated by Django 3.2.11 on 2022-03-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefin', models.DateTimeField()),
                ('content', models.FileField(max_length=15, upload_to='none')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.classroom')),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.matter')),
                ('professor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson.professor')),
            ],
        ),
    ]
